MVCInBuiltFeatures/Models/Library.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCInBuiltFeatures.Models
{
    public class Library
    {

        public int LibraryID { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Pole {0} musi zawierać przynajmniej {2} liter.", MinimumLength = 6)]
        [Display(Name = "Nazwa biblioteki")]
        public string Name { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Pole {0} musi zawierać przynajmniej {2} liter.", MinimumLength = 6)]
        [Display(Name = "Miejscowość")]
        public string City { get; set; }
        [StringLength(100, ErrorMessage = "Pole {0} musi zawierać przynajmniej {2} liter.", MinimumLength = 6)]
        [Display(Name = "Ulica")]
        public string Street { get; set; }
    }
}

MVCInBuiltFeatures/Controllers/LibrariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCInBuiltFeatures.Models;
using PagedList;


namespace MVCInBuiltFeatures.Controllers
{
    public class LibrariesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        // GET: Libraries
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";
            ViewBag.CitySortParm = sortOrder == "City" ? "city_desc" : "City";
            ViewBag.StreetSortParm = sortOrder == "Street" ? "street_desc" : "Street";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            IQueryable<Library> libraries = db.Libraries;

            if (!String.IsNullOrEmpty(searchString))
            {
                libraries = libraries.Where(b => b.Name.Contains(searchString)
                                       || b.City.Contains(searchString)
                                       || b.Street.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    libraries = libraries.OrderByDescending(l => l.Name);
                    break;
                case "city_desc":
                    libraries = libraries.OrderByDescending(l => l.City);
                    break;
                case "street_desc":
                    libraries = libraries.OrderByDescending(l => l.Street);
                    break;
                case "Name":
                    libraries = libraries.OrderBy(l => l.Name);
                    break;
                case "City":
                    libraries = libraries.OrderBy(l => l.City);
                    break;
                case "Street":
                    libraries = libraries.OrderBy(l => l.Street);
                    break;
                default:
                    libraries = libraries.OrderBy(l => l.LibraryID);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(libraries.ToPagedList(pageNumber, pageSize));
        }

        // GET: Libraries/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Library library = db.Libraries.Find(id);
            if (library == null)
            {
                return HttpNotFound();
            }
            return View(library);
        }

        // GET: Libraries/Create
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Libraries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Create([Bind(Include = "LibraryID,Name,City,Street")] Library library)
        {
            if (ModelState.IsValid)
            {
                db.Libraries.Add(library);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(library);
        }

        // GET: Libraries/Edit/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Library library = db.Libraries.Find(id);
            if (library == null)
            {
                return HttpNotFound();
            }
            return View(library);
        }

        // POST: Libraries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LibraryID,Name,City,Street")] Library library)
        {
            if (ModelState.IsValid)
            {
                db.Entry(library).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(library);
        }

        // GET: Libraries/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Library library = db.Libraries.Find(id);
            if (library == null)
            {
                return HttpNotFound();
            }
            return View(library);
        }

        // POST: Libraries/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Library library = db.Libraries.Find(id);
            db.Libraries.Remove(library);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCInBuiltFeatures/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using MVCInBuiltFeatures.Models;
using System.Threading.Tasks;

namespace MVCInBuiltFeatures.Controllers
{
    public class LibraryController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: api/Library
        public IQueryable<Library> GetLibraries()
        {
            return db.Libraries;
        }

        // GET: api/Library/5
        [ResponseType(typeof(Library))]
        public async Task<IHttpActionResult> GetLibrary(int id)
        {
            Library library = await db.Libraries.FindAsync(id);
            if (library == null)
            {
                return NotFound();
            }

            return Ok(library);
        }

        // PUT: api/Library/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutLibrary(int id, Library library)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != library.LibraryID)
            {
                return BadRequest();
            }

            db.Entry(library).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LibraryExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Library
        [ResponseType(typeof(Library))]
        public async Task<IHttpActionResult> PostLibrary(Library library)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Libraries.Add(library);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = library.LibraryID }, library);
        }

        // DELETE: api/Library/5
        [ResponseType(typeof(Library))]
        public async Task<IHttpActionResult> DeleteLibrary(int id)
        {
            Library library = await db.Libraries.FindAsync(id);
            if (library == null)
            {
                return NotFound();
            }

            db.Libraries.Remove(library);
            await db.SaveChangesAsync();

            return Ok(library);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool LibraryExists(int id)
        {
            return db.Libraries.Count(e => e.LibraryID == id) > 0;
        }
    }
}

MVCInBuiltFeatures/Views/Libraries/Create.cshtml
@model MVCInBuiltFeatures.Models.Library

@{
    ViewBag.Title = "Stwórz bibliotekę";
}

<h2>Stwórz bibilotekę</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Biblioteka</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index", null, new { @class = "btn btn-default" })
</div>

MVCInBuiltFeatures/Views/Libraries/Delete.cshtml
@model MVCInBuiltFeatures.Models.Library

@{
    ViewBag.Title = "Usuń bibliotekę";
}

<h2>Usuń bibliotekę</h2>

<h3>Jesteś pewien że chcesz usunąć tą bibliotekę ?</h3>
<div>
    <h4>Biblioteka</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Powrót do listy", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

MVCInBuiltFeatures/Views/Libraries/Details.cshtml
@model MVCInBuiltFeatures.Models.Library

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły biblioteki</h2>

<div>
    <h4>Biblioteka</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

    </dl>
</div>
<p>
    @if ((Request.IsAuthenticated && User.IsInRole("Admin")) || (Request.IsAuthenticated && User.IsInRole("Moderator")))
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.LibraryID }, new { @class = "btn btn-default" })
    }
    @Html.ActionLink("Powrót do listy", "Index", null, new { @class = "btn btn-default" })
</p>

MVCInBuiltFeatures/Views/Libraries/Edit.cshtml
@model MVCInBuiltFeatures.Models.Library

@{
    ViewBag.Title = "Edycja biblioteki";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Biblioteka</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LibraryID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index", null, new { @class = "btn btn-default" })
</div>

MVCInBuiltFeatures/Views/Libraries/Index.cshtml
@model PagedList.IPagedList<MVCInBuiltFeatures.Models.Library>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Biblioteki";
}

<h2>Lista bibliotek</h2>

<p>
@if ((Request.IsAuthenticated && User.IsInRole("Admin")) || (Request.IsAuthenticated && User.IsInRole("Moderator")))
{
    @Html.ActionLink("Dodaj bibliotekę", "Create", null, new { @class = "btn btn-primary" })
}
</p>
@using (Html.BeginForm("Index", "Libraries", FormMethod.Get))
{
    <p>
        Wyszukaj: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Szukaj</button>
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Nazwa biblioteki", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Miasto", "Index", new { sortOrder = ViewBag.CitySortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Ulica", "Index", new { sortOrder = ViewBag.StreetSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Street)
        </td>
        <td>
            <div class="btn-group">
                @Html.ActionLink("Szczegóły", "Details", null, new { id = item.LibraryID }, new { @class = "btn btn-default" })
                @if ((Request.IsAuthenticated && User.IsInRole("Admin")) || (Request.IsAuthenticated && User.IsInRole("Moderator")))
                {
                    @Html.ActionLink("Edytuj", "Edit", null, new { id = item.LibraryID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Usuń", "Delete", null, new { id = item.LibraryID }, new { @class = "btn btn-default" })
                }
            </div>

</td>
    </tr>
}

</table>
<br />
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))